### ISSUE TITLE
 Will five images predict one key value or five images predict five key values?

### ISSUE THREAD

**Issue by Zhangshuor** [ikergarcia1996/Self-Driving-Car-in-Video-Games#11]
Hi！When running the model, five images are a sequence. Will five images predict one key value or five images predict five key values?
Thank you!!
<img width="675" alt="image" src="https://user-images.githubusercontent.com/78637328/169958506-9a77c385-160c-4f4b-b5bd-d96fbf324960.png">

**Comment by ikergarcia1996** [comment]
Hi! The model predicts one key value (or a controller input, two floats, if you want to use a xbox controller instead of the keyboard) for each sequence of five images. 
This is done because at the time I created the training dataset I only saved the key value for the last image of each sequence. It would be cool to create a new dataset that contains the key value for each image (the current version of the script that captures data does it, and the dev/test sets have the key value for each image, but the train set was crated using a previous version of the script), that would allow implementing different architectures such as autoregresive transformer decoders. Unfortunately, creating a new train dataset with more than 100Gb of data is a task that requires a lot of work.
